# Generated by Django 5.2.8 on 2025-11-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('spend', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('status', models.CharField(choices=[('IN_BUDGET', 'In Budget'), ('WARNING', 'Warning'), ('OUT_OF_BUDGET', 'Out of Budget')], default='IN_BUDGET', max_length=20)),
            ],
        ),
    ]
